# -*- coding: utf-8 -*-
"""streamlit_dt_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XObJlUh3zMrstsRJVg0uhtV14ak4s6gQ
"""

import os
import numpy as np
import pandas as pd
import streamlit as st

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import recall_score, precision_score, accuracy_score, f1_score

# ----------------------------------------------------------
# Page config
# ----------------------------------------------------------
st.set_page_config(
    page_title="Cervical Cancer Risk Prediction",
    page_icon="🔬",
    layout="centered",
)

# ----------------------------------------------------------
# Title & description
# ----------------------------------------------------------
st.title("🔬 Cervical Cancer Risk Prediction Tool")

# ----------------------------------------------------------
# Extra context
# ----------------------------------------------------------
with st.expander("ℹ️ About this Decision Tree model"):
    st.markdown(
        """
**Model type:** Shallow Decision Tree (max_depth=3)
**Why this model?**

- Achieved one of the **highest Recall scores** in MLflow experiments
- Also maintained **high Precision and Accuracy**, unlike extreme Naive Bayes runs
- Easy to interpret: decisions can be visualized as a tree structure

**Metric priority:**
Recall (Sensitivity) is prioritized to reduce the chance of missing true cancer cases,
while still keeping precision and overall accuracy at acceptable levels.
"""
    )

st.write(
    """
This app uses a **shallow Decision Tree classifier** to estimate the risk of a
**positive cervical cancer biopsy** based on demographic, behavioral, and clinical features.

> **Important:** This tool is for **educational purposes only** (CIS 508 project)
> and is **not** a medical device or diagnostic tool.
"""
)

st.markdown("---")


# ----------------------------------------------------------
# 1. Load data & train best Decision Tree (cached)
# ----------------------------------------------------------
@st.cache_resource
def load_and_train_dt_model():
    """
    Load the cervical cancer dataset, train the best Decision Tree model
    (based on Databricks/MLflow experiments), and return the model + preprocessors.
    """

    csv_path = os.path.join(os.path.dirname(__file__), "risk_factors_cervical_cancer.csv")

    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Dataset not found at:\n{csv_path}\n\n"
            "Make sure 'risk_factors_cervical_cancer.csv' is in the same folder "
            "as this script."
        )

    df = pd.read_csv(csv_path)

    # Basic cleaning
    df.replace("?", np.nan, inplace=True)
    df = df.apply(pd.to_numeric, errors="ignore")
    df.dropna(subset=["Biopsy"], inplace=True)

    # Same feature set as XGBoost app for consistency
    feature_cols = [
        "Age",
        "Number of sexual partners",
        "First sexual intercourse",
        "Num of pregnancies",
        "Smokes",
        "Smokes (years)",
        "Smokes (packs/year)",
        "Hormonal Contraceptives",
        "Hormonal Contraceptives (years)",
        "IUD",
        "IUD (years)",
        "STDs",
        "STDs (number)",
        "Dx:Cancer",
        "Dx:CIN",
        "Dx:HPV",
    ]

    X = df[feature_cols]
    y = df["Biopsy"]

    # Preprocessing: impute + scale (to match training used in your experiments)
    imputer = SimpleImputer(strategy="median")
    X_imputed = imputer.fit_transform(X)

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42, stratify=y
    )

    # Best Decision Tree hyperparameters (from MLflow runs)
    dt = DecisionTreeClassifier(
        max_depth=3,
        min_samples_split=2,
        criterion="gini",
        random_state=42,
    )

    dt.fit(X_train, y_train)

    # Evaluate on test set
    y_pred = dt.predict(X_test)
    recall = recall_score(y_test, y_pred, zero_division=0)
    precision = precision_score(y_test, y_pred, zero_division=0)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, zero_division=0)

    metrics = {
        "recall": recall,
        "precision": precision,
        "accuracy": acc,
        "f1": f1,
    }

    return dt, imputer, scaler, feature_cols, metrics


try:
    dt_model, imputer, scaler, FEATURE_COLS, dt_metrics = load_and_train_dt_model()
    st.success(
        "✅ Decision Tree trained successfully.\n\n"
        f"**Validation performance (test set):**  \n"
        f"- Recall: `{dt_metrics['recall']:.3f}`  \n"
        f"- Precision: `{dt_metrics['precision']:.3f}`  \n"
        f"- Accuracy: `{dt_metrics['accuracy']:.3f}`  \n"
        f"- F1-score: `{dt_metrics['f1']:.3f}`"
    )
except Exception as e:
    st.error(
        "❌ Could not load or train the Decision Tree model.\n\n"
        f"Details: `{e}`"
    )
    st.stop()


st.markdown("### Enter Patient Information")


# ----------------------------------------------------------
# 2. User input widgets (must match FEATURE_COLS order)
# ----------------------------------------------------------
def yes_no_to_int(answer: str) -> int:
    return 1 if answer == "Yes" else 0


col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age", min_value=15, max_value=90, value=30, step=1)
    num_partners = st.number_input(
        "Number of sexual partners", min_value=0, max_value=30, value=1, step=1
    )
    first_sex = st.number_input(
        "Age at first sexual intercourse", min_value=10, max_value=40, value=18, step=1
    )
    num_preg = st.number_input(
        "Number of pregnancies", min_value=0, max_value=20, value=0, step=1
    )
    smokes = st.selectbox("Smokes?", ["No", "Yes"])
    smokes_years = st.number_input(
        "Years of smoking", min_value=0.0, max_value=50.0, value=0.0, step=0.5
    )
    smokes_packs = st.number_input(
        "Packs of cigarettes per year", min_value=0.0, max_value=100.0, value=0.0, step=0.5
    )

with col2:
    hormonal = st.selectbox("Uses hormonal contraceptives?", ["No", "Yes"])
    hormonal_years = st.number_input(
        "Years of hormonal contraceptive use", min_value=0.0, max_value=40.0, value=0.0, step=0.5
    )
    iud = st.selectbox("Uses IUD?", ["No", "Yes"])
    iud_years = st.number_input(
        "Years of IUD use", min_value=0.0, max_value=40.0, value=0.0, step=0.5
    )
    stds_any = st.selectbox("History of any STD?", ["No", "Yes"])
    stds_number = st.number_input(
        "Number of STDs", min_value=0.0, max_value=20.0, value=0.0, step=1.0
    )
    dx_cancer = st.selectbox("Previous diagnosis: Cancer?", ["No", "Yes"])
    dx_cin = st.selectbox("Previous diagnosis: CIN?", ["No", "Yes"])
    dx_hpv = st.selectbox("Previous diagnosis: HPV?", ["No", "Yes"])


st.markdown("---")
st.subheader("Decision Tree Prediction")


# ----------------------------------------------------------
# 3. Prepare features & predict
# ----------------------------------------------------------
if st.button("Predict Biopsy Risk"):

    raw_input = np.array(
        [[
            age,
            num_partners,
            first_sex,
            num_preg,
            yes_no_to_int(smokes),
            smokes_years,
            smokes_packs,
            yes_no_to_int(hormonal),
            hormonal_years,
            yes_no_to_int(iud),
            iud_years,
            yes_no_to_int(stds_any),
            stds_number,
            yes_no_to_int(dx_cancer),
            yes_no_to_int(dx_cin),
            yes_no_to_int(dx_hpv),
        ]]
    )

    try:
        X_imp = imputer.transform(raw_input)
        X_scaled = scaler.transform(X_imp)

        pred = dt_model.predict(X_scaled)[0]

        # Decision trees don't have calibrated probabilities by default,
        # but predict_proba is available:
        prob_text = ""
        if hasattr(dt_model, "predict_proba"):
            proba = dt_model.predict_proba(X_scaled)[0][1]
            prob_text = f"\n\nEstimated probability of **positive biopsy**: `{proba:.3f}`"

        if int(pred) == 1:
            st.error(
                "⚠️ **High predicted risk of a positive cervical cancer biopsy.**"
                + prob_text
                + "\n\nIn a clinical context, this would indicate elevated risk and the need for further evaluation."
            )
        else:
            st.success(
                "✅ **Low predicted risk of a positive cervical cancer biopsy.**"
                + prob_text
                + "\n\nRoutine screening is still important according to medical guidelines."
            )

    except Exception as e:
        st.error(
            "❌ Prediction failed due to an internal error.\n\n"
            f"Details: `{e}`"
        )




st.caption(
    "CIS 508 Final Project – Decision Tree cervical cancer risk model · Educational use only."
)
